version: 0.2

phases:
  install:
    commands:
      - echo Installing...

  pre_build:
    commands:

      - echo Logging in to DockerHub...
      - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

  build:
    commands:
      - docker build -t $DOCKER_USER/devops-app:latest .

      - IMAGE_TAG=$(date +%s)
      - docker build -t $DOCKER_USER/devops-app:$IMAGE_TAG .
      - docker tag $DOCKER_USER/devops-app:$IMAGE_TAG $DOCKER_USER/devops-app:latest


  post_build:
    commands:
      - docker push $DOCKER_USER/devops-app:latest
      - docker push $DOCKER_USER/devops-app:$IMAGE_TAG
      
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name devops-eks

      - echo Scaling down old pods...
      - kubectl scale deployment devops-app --replicas=0



      - echo Deploying to EKS...
      - kubectl set image deployment/devops-app devops-app=$DOCKER_USER/devops-app:$IMAGE_TAG

      - echo Scaling up...
      - kubectl scale deployment devops-app --replicas=1



